**Sonal Shukla (CS23176)**

**Lab-5 Assignment-1 : To implement the Random Forest algorithm on the Gaming and Mental Health dataset and evaluate the model performance using appropriate metrics.**

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
path="/content/drive/MyDrive/ML_DATASETS/Gaming and Mental Health - Gaming and Mental Health.csv"
df=pd.read_csv(path)
df.head(5)

,record_id,age,gender,daily_gaming_hours,game_genre,primary_game,gaming_platform,sleep_hours,sleep_quality,sleep_disruption_frequency,...,continued_despite_problems,eye_strain,back_neck_pain,weight_change_kg,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,years_gaming,gaming_addiction_risk_level
0,GD0001,17,Male,11.1,Mobile Games,Clash of Clans,PC,3.7,Very Poor,Sometimes,...,True,True,False,6.8,3.7,7,1.3,383.70,3,Severe
1,GD0002,21,Male,3.0,MOBA,Dota 2,PC,7.2,Fair,Rarely,...,False,False,False,0.4,8.5,2,10.7,46.64,1,Low
2,GD0003,23,Male,7.6,FPS,CS:GO,Multi-platform,4.4,Fair,Often,...,True,False,True,1.8,7.1,5,3.2,100.81,6,Severe
3,GD0004,20,Female,7.2,RPG,Skyrim,Multi-platform,5.1,Fair,Often,...,False,True,True,0.2,5.2,4,9.1,51.60,7,High
4,GD0005,18,Male,6.8,Battle Royale,Apex Legends,PC,3.4,Poor,Never,...,False,False,False,0.5,6.1,4,4.5,32.57,1,Moderate

In [ ]:
df.shape

(1000, 27)

In [ ]:
df.columns

Index(['record_id', 'age', 'gender', 'daily_gaming_hours', 'game_genre',
       'primary_game', 'gaming_platform', 'sleep_hours', 'sleep_quality',
       'sleep_disruption_frequency', 'academic_work_performance', 'grades_gpa',
       'work_productivity_score', 'mood_state', 'mood_swing_frequency',
       'withdrawal_symptoms', 'loss_of_other_interests',
       'continued_despite_problems', 'eye_strain', 'back_neck_pain',
       'weight_change_kg', 'exercise_hours_weekly', 'social_isolation_score',
       'face_to_face_social_hours_weekly', 'monthly_game_spending_usd',
       'years_gaming', 'gaming_addiction_risk_level'],
      dtype='object')

In [ ]:
df.isnull().any().any()

np.True_

In [ ]:
df[df.isnull().any(axis = 1)]

,record_id,age,gender,daily_gaming_hours,game_genre,primary_game,gaming_platform,sleep_hours,sleep_quality,sleep_disruption_frequency,...,continued_despite_problems,eye_strain,back_neck_pain,weight_change_kg,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,years_gaming,gaming_addiction_risk_level
0,GD0001,17,Male,11.1,Mobile Games,Clash of Clans,PC,3.7,Very Poor,Sometimes,...,True,True,False,6.8,3.7,7,1.3,383.70,3,Severe
2,GD0003,23,Male,7.6,FPS,CS:GO,Multi-platform,4.4,Fair,Often,...,True,False,True,1.8,7.1,5,3.2,100.81,6,Severe
4,GD0005,18,Male,6.8,Battle Royale,Apex Legends,PC,3.4,Poor,Never,...,False,False,False,0.5,6.1,4,4.5,32.57,1,Moderate
7,GD0008,28,Female,10.3,Mobile Games,Clash of Clans,Console,5.2,Fair,Sometimes,...,True,True,True,2.4,5.6,6,0.2,299.28,13,Severe
8,GD0009,18,Male,1.4,Mobile Games,Genshin Impact,PC,8.9,Poor,Always,...,False,False,False,0.1,10.1,1,12.9,49.40,6,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,GD0996,15,Female,8.6,Strategy,Age of Empires,PC,4.1,Very Poor,Always,...,True,True,True,1.9,7.5,6,2.4,426.54,3,Severe
996,GD0997,18,Male,5.4,MMO,Elder Scrolls Online,Multi-platform,6.5,Fair,Never,...,False,True,False,2.1,7.7,1,10.9,83.71,7,Low
997,GD0998,23,Male,7.3,RPG,Skyrim,PC,3.9,Insomnia,Rarely,...,False,False,True,0.5,8.1,5,6.7,88.60,5,High
998,GD0999,18,Male,3.1,Strategy,StarCraft II,Console,8.2,Fair,Sometimes,...,False,False,False,0.8,8.4,1,12.7,22.02,8,Low
999,GD1000,29,Male,3.5,RPG,Cyberpunk 2077,Multi-platform,7.4,Good,Sometimes,...,False,False,False,0.0,9.3,2,10.9,25.20,19,Low

In [ ]:
X = df.drop(columns=['gaming_addiction_risk_level'])
y = df['gaming_addiction_risk_level']

In [ ]:
X.head()

,record_id,age,gender,daily_gaming_hours,game_genre,primary_game,gaming_platform,sleep_hours,sleep_quality,sleep_disruption_frequency,...,loss_of_other_interests,continued_despite_problems,eye_strain,back_neck_pain,weight_change_kg,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,years_gaming
0,GD0001,17,Male,11.1,Mobile Games,Clash of Clans,PC,3.7,Very Poor,Sometimes,...,False,True,True,False,6.8,3.7,7,1.3,383.70,3
1,GD0002,21,Male,3.0,MOBA,Dota 2,PC,7.2,Fair,Rarely,...,False,False,False,False,0.4,8.5,2,10.7,46.64,1
2,GD0003,23,Male,7.6,FPS,CS:GO,Multi-platform,4.4,Fair,Often,...,True,True,False,True,1.8,7.1,5,3.2,100.81,6
3,GD0004,20,Female,7.2,RPG,Skyrim,Multi-platform,5.1,Fair,Often,...,True,False,True,True,0.2,5.2,4,9.1,51.60,7
4,GD0005,18,Male,6.8,Battle Royale,Apex Legends,PC,3.4,Poor,Never,...,False,False,False,False,0.5,6.1,4,4.5,32.57,1

In [ ]:
X = pd.get_dummies(X,dtype = int)

In [ ]:
X.head()

,age,daily_gaming_hours,sleep_hours,grades_gpa,work_productivity_score,withdrawal_symptoms,loss_of_other_interests,continued_despite_problems,eye_strain,back_neck_pain,...,mood_state_Excited,mood_state_Irritable,mood_state_Normal,mood_state_Restless,mood_state_Withdrawn,mood_swing_frequency_Daily,mood_swing_frequency_Never,mood_swing_frequency_Often,mood_swing_frequency_Rarely,mood_swing_frequency_Sometimes
0,17,11.1,3.7,1.25,NaN,True,False,True,True,False,...,0,0,0,0,0,0,1,0,0,0
1,21,3.0,7.2,3.75,2.0,False,False,False,False,False,...,0,1,0,0,0,0,0,1,0,0
2,23,7.6,4.4,NaN,9.0,True,True,True,False,True,...,0,1,0,0,0,0,0,0,1,0
3,20,7.2,5.1,1.62,2.0,True,True,False,True,True,...,0,0,0,0,1,1,0,0,0,0
4,18,6.8,3.4,2.44,NaN,True,False,False,False,False,...,0,0,0,0,0,1,0,0,0,0

In [ ]:
X.shape

(1000, 1084)

In [ ]:
X.columns

Index(['age', 'daily_gaming_hours', 'sleep_hours', 'grades_gpa',
       'work_productivity_score', 'withdrawal_symptoms',
       'loss_of_other_interests', 'continued_despite_problems', 'eye_strain',
       'back_neck_pain',
       ...
       'mood_state_Excited', 'mood_state_Irritable', 'mood_state_Normal',
       'mood_state_Restless', 'mood_state_Withdrawn',
       'mood_swing_frequency_Daily', 'mood_swing_frequency_Never',
       'mood_swing_frequency_Often', 'mood_swing_frequency_Rarely',
       'mood_swing_frequency_Sometimes'],
      dtype='object', length=1084)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.7,test_size=0.3,random_state=42)
X_train.shape,X_test.shape

((700, 1084), (300, 1084))

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=100,n_jobs=-1,max_depth=5,oob_score=True,random_state=42)
rf_classifier.fit(X_train,y_train)

RandomForestClassifier(max_depth=5, n_jobs=-1, oob_score=True, random_state=42)

In [ ]:
y_pred = rf_classifier.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [ ]:
print('Confusion Matrix')
cm=confusion_matrix(y_test,y_pred)
print(confusion_matrix(y_test,y_pred))

Confusion Matrix
[[ 21   9  17   5]
 [  0 148   0   0]
 [  8  38   4   0]
 [  8   1   7  34]]

In [ ]:
print('Accuracy Score')
print(accuracy_score(y_test,y_pred))

Accuracy Score
0.69

In [ ]:
rf_classifier.oob_score_

0.6914285714285714

In [ ]:
print('Classification Report')
print(classification_report(y_test,y_pred))

Classification Report
              precision    recall  f1-score   support

        High       0.57      0.40      0.47        52
         Low       0.76      1.00      0.86       148
    Moderate       0.14      0.08      0.10        50
      Severe       0.87      0.68      0.76        50

    accuracy                           0.69       300
   macro avg       0.58      0.54      0.55       300
weighted avg       0.64      0.69      0.65       300

In [ ]:
rf=RandomForestClassifier(random_state=42,n_jobs=-1)
params={
    'max_depth':[2,3,5],
    'min_samples_leaf':[5,10,20],
    'n_estimators':[10,25,30,50]
}
from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(estimator=rf, param_grid=params, cv = 4, n_jobs=-1,verbose=1, scoring="accuracy")
grid_search.fit(X_train,y_train)

Fitting 4 folds for each of 36 candidates, totalling 144 fits

GridSearchCV(cv=4, estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
             n_jobs=-1,
             param_grid={'max_depth': [2, 3, 5],
                         'min_samples_leaf': [5, 10, 20],
                         'n_estimators': [10, 25, 30, 50]},
             scoring='accuracy', verbose=1)

In [ ]:
grid_search.best_score_

np.float64(0.6185714285714285)

In [ ]:
print(grid_search.best_params_)

{'max_depth': 5, 'min_samples_leaf': 5, 'n_estimators': 50}